### ISSUE TITLE
$$-class error with Handlebars

### ISSUE THREAD

**Issue by psnoname** [christianalfoni/jflux#1]
Hi christianalfoni,
i cant use the $$-class attribute in my handlebar template.
I got the following error message, line 403 in jflux-1.2.2.js:

```
InvalidCharacterError: String contains an invalid character
node.setAttribute(attrName, attrValue)
```

My handlebar template looks like this:

```
<div>
    <button $$-class="powerClasses">{{ powerBtnText }}</button>
    <br />
    has power: {{ powerStatus }}
    <br />
    {{#myTextComponent}}{{/myTextComponent}}
</div>
```

Without the $$-class attribute all goes fine

**Comment by christianalfoni** [comment]
Hi @PSnOnAmE!

It might not be too clear in the documentation that the $$- syntax is for the "compiled mode" only. When using Handlebars you already have the templating syntax, so to reduce complexity I chose not to extend the templating syntax of Handlebars with $$-.

I suggest you use the render method and configure a property for the css class:

``` javascript
var myComponent = $$.component({
  template: Handlebars.templates.myTemplate,
  render: function () {
    this.powerClasses = isTrue ? 'success' : 'error';
    return this.template(this);
  }
});
```

``` html
<div>
    <button class="{{ powerClasses }}">{{ powerBtnText }}</button>
    <br />
    has power: {{ powerStatus }}
    <br />
    {{#myTextComponent}}{{/myTextComponent}}
</div>
```

I hope this was of help to you, or please let me know if you have any more questions :-)

**Comment by psnoname** [comment]
ah okay, thank you for the fast reply!
